### ISSUE TITLE
Choosing a good QC metric?

### ISSUE THREAD

**Issue by jlhanson5** [BIDS-Apps/mriqc#4]
Hello mriqc repo,

I wondered if folks had specific thoughts on choosing an image QC metric (for structural MRIs)? I read over the IQMs page on http://mriqc.readthedocs.io, and had a sense of what the specific variables are measuring; however, I wondered if folks had thoughts on choosing an "aggregated" measure?

I was thinking about this from a few perspectives:
-Analytically, I wondered "Is QC Metric X related to variable Y?" (having one variable would make that easier to conceptualize and analyze),
-From a novel statistical perspective (perhaps I could covary an aggregated QC measure to make sure noise wasn't driving any statistical relations?),
-And a simple reporting perspective (group 1 has this average QC; group 2 has this average in a manuscript). 

I thought about using the probabilities from the mriqc classifier (but I didn't have the strongest sense of how that was calculated). Any thoughts are greatly appreciated! Thanks much!

Best,
Jamie.

**Comment by chrisfilo** [comment]
The crowdsourced QC metrics might be useful for those purposes:

https://gist.github.com/chrisfilo/eccdb8b98f8e74d24a3395a49fbadf03
https://mriqc.nimh.nih.gov/
